### PR TITLE
Implement ArithmeticSequenceValidator

### LINKED ISSUE #1: Implement ArithmeticSequenceValidator
## Missing Implementation

Implement the [`is_arithemtic_sequence`][0] method to return `True` if the passed list of integers contains a sequence (123, 5678, 4321, etc.) of length `self.n` or more.

[0]: https://github.com/Blueshoe/django-secure-passwords/blob/9550c452531b0f7dbb4be4cc181d69f2a10aac33/securepasswords/validators.py#L61

### PR DESCRIPTION
**Pull request by saurabhlanjewar**
Implement the is_arithemtic_sequence method to return True if the passed list of integers contains a sequence (123, 5678, 4321, etc.) of length self.n or more.

### CODE REVIEW

**Comment by saurabhlanjewar** [comment]
i have implemented the arithemetic sequence validator

**Comment by Schille** [comment]
Hi @saurabhlanjewar thank you for your contribution. Please provide a unit test for your function, too. You can install the project dependencies from `requirements.txt`, add your testcase and run `python manage.py test`.

**Comment by saurabhlanjewar** [comment]
self.n is max length of contiguous number if we give [3, 3, 2, 1, 5] and set self.n = 3 if means that we can enter maximum 3 contiguous number if should return false because user have not enter the password longer than and if self.n = 2 then we should return true beacause user entered contiguous number longer than 2


let me know if i am wrong so i can correct my mistake

**Comment by saurabhlanjewar** [comment]
so i update the ArithmeticSequenceValidator method and i have added test case

**Comment by saurabhlanjewar** [comment]
Screenshot (161)

**Comment by vvvityaaa** [comment]
Hi @saurabhlanjewar. Right now the pipeline fails because of the black code style error. The reason is probably, that you did not install pre-commit (https://pre-commit.com/) before committing changes. To fix this problem, you can either install pre-commit and then make some changes in the file and then commit once again. This way pre-commits would run and your code would be reformatted according to pre-commit specification. 
Another way is to install black code style (https://pypi.org/project/black/) and run command `black --line-length=120 --check <path_to_the_file> `. This way you will get safely the information, whether this file should be changed or not. Then applying the same command without check `black --line-length=120 <path_to_the_file> ` would change your file and you could then safely commit the changes to the file.

**Comment by vvvityaaa** [comment]
@saurabhlanjewar Thank you for the quick fix. Unfortunately, I cannot see the test case, that you were mentioning, did you commit it?

**Comment by saurabhlanjewar** [comment]
sorry i forget to commit test case now i have added the test case  you can check that

**Comment by vvvityaaa** [comment]
@saurabhlanjewar please also merge current master branch into your branch and resolve conflicts. Also please fix the typos in the test names `test_d_set_arthemetic_sequence_password` to `test_d_set_arithmetic_sequence_password` and `test_d_set_ramdom_sequence_password` to `test_d_set_random_sequence_password`. Thank you

**Comment by saurabhlanjewar** [comment]
resolved the problem regrading typo error and merge conflict

**Comment by Schille** [comment]
Please remove those `.idea/...` files from your PR, the code seems to be fine.

**Comment by saurabhlanjewar** [comment]
now i have removed all ./idea files from my PR

**Comment by saurabhlanjewar** [comment]
is everything right with my code

**Comment by schwobaseggl** [comment]
@saurabhlanjewar 
The code is fine functionally now, but it is still a little complicated. I have submitted a simplified version that also has more tests (using different `max_length` parameters). Check out https://github.com/Blueshoe/django-secure-passwords/pull/16.
I am closing this PR, but don't feel discouraged to contribute in the future.

**Pull request closed without merging**
